{{- if .Values.mlflow.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-voice-agent.fullname" . }}-mlflow
  labels:
    {{- include "ai-voice-agent.mlflow.labels" . | nindent 4 }}
  {{- if .Values.mlflow.oauth.enabled }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "ai-voice-agent.fullname" . }}-mlflow"}}'
  {{- end }}
{{- end }}
