{{- if .Values.backend.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-voice-agent.fullname" . }}-backend
  labels:
    {{- include "ai-voice-agent.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.backend.secret.API_KEY | quote }}
  TTS_API_KEY: {{ .Values.backend.secret.TTS_API_KEY | default .Values.backend.secret.API_KEY | quote }}
  STT_TOKEN: {{ .Values.backend.secret.STT_TOKEN | quote }}
{{- end }}
