---
apiVersion: v1
kind: Service
metadata:
  name: voice-web
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-notebook
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    statefulset: voice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-ingress
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
  podSelector: {}
  policyTypes:
  - Ingress
---
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  name: voice-web
spec:
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: voice-web
    weight: 100
  wildcardPolicy: None
status: {}
